### 1 统计相关的函数

In [1]:
import torch
import pandas as pd
import numpy as np

In [2]:
# 1 torch.mean()
a = torch.tensor([3, 4, 5, 6], dtype=torch.float)

torch.mean(a)

tensor(4.5000)

In [3]:
# 2 torch.sum()

torch.sum(a)

tensor(18.)

In [4]:
# 3 torch.prod() 计算所有元素的积
torch.prod(a)

tensor(360.)

In [5]:
# 4. torch.max()

torch.max(a)

tensor(6.)

In [6]:
# 5. torch.min()

torch.min(a)

tensor(3.)

In [7]:
# 6. torch.argmax()

torch.argmax(a)

tensor(3)

In [8]:
# 7. torch.argmin()

torch.argmin(a)

tensor(0)

In [9]:
# 8. torch.std()

torch.std(a)

tensor(1.2910)

In [10]:
# 9. torch.var()

torch.var(a)

tensor(1.6667)

In [11]:
# 10. torch.median()

torch.median(a)

tensor(4.)

In [12]:
# 11. torch.mode() 众数值

torch.mode(a)

torch.return_types.mode(
values=tensor(3.),
indices=tensor(0))

In [13]:
# 12. 直方图

torch.histc(a)

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [14]:
# 13. 定义随机种子

torch.manual_seed(222)

In [15]:
# 14. 组合 / 拼接 按照已经存在的维度进行拼接
a1 = torch.tensor([1, 2, 3], dtype=torch.float)
a2 = torch.tensor([4, 5, 6], dtype=torch.float)

torch.cat([a1, a2], dim=0)

tensor([1., 2., 3., 4., 5., 6.])

In [16]:
# 15. 组合 / 拼接 按照新的纬度进行拼接
a1 = torch.tensor([1, 2, 3], dtype=torch.float)
a2 = torch.tensor([4, 5, 6], dtype=torch.float)

torch.stack([a1, a2], dim=1)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [17]:
torch.stack([a1, a2], dim=0)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [18]:
# 16. torch.where(condition, x, y) : 按照条件从x和y中选出满足条件的元素组成新的tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

y = torch.tensor([11, 22, 33, 44, 55, 66])

torch.where(x > 6) # 输出对应的索引值

(tensor([2, 2, 2]), tensor([0, 1, 2]))

In [19]:
# 17. torch.gather(input, dim, index, out=None)
# 在指定维度上按照索引赋值输出tensor

b = torch.Tensor([[1,2,3],[4,5,6]])
index_1 = torch.LongTensor([[0,1],[2,0]])
index_2 = torch.LongTensor([[0,1,1],[0,0,0]])

print(torch.gather(b, dim=1, index=index_1))

print(torch.gather(b, dim=0, index=index_2))

tensor([[1., 2.],
        [6., 4.]])
tensor([[1., 5., 6.],
        [1., 2., 3.]])


In [20]:
# 18. torch.index_select(input, dim, index, out=None) : 按照指定索引输出tensor

a = torch.linspace(1, 12, steps=12).view(3, 4)
print(a)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [21]:
b = torch.index_select(a, 0, torch.tensor([0, 2]))
print(b)

tensor([[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]])


In [22]:
c = torch.index_select(a, 1, torch.tensor([0, 2]))
print(c)

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])


In [45]:
# 19. Tensor 与 tensor 的区别
a = torch.Tensor([1, 2])
print(a)

b = torch.tensor([3, 4])
print(b)

tensor([1., 2.])
tensor([3, 4])


In [24]:
print(a.type())

torch.FloatTensor


In [25]:
print(b.type())

torch.LongTensor


In [26]:
torch.tensor(5.6)

tensor(5.6000)

In [44]:
torch.Tensor(5.6) # 会报错，需要输入一个向量

TypeError: new(): data must be a sequence (got float)

In [28]:
torch.Tensor([5.6])

tensor([5.6000])

In [29]:
# 20. torch.masked_select(input, mask, out=None) : 按照mask输出tensor，输出为向量。

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
mask = x.ge(5) # x >= 5 的为True
mask

tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])

In [30]:
torch.masked_select(x, mask)

tensor([5, 6, 7, 8, 9])

In [31]:
# 21. torch.take(input, indices) : 将输入看成1D-tensor，按照索引得到输出tensor
src = torch.tensor([[4,3,5],
                    [6,7,8]])

torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

In [32]:
# 22 tensor 切片 : tensor.chunk(tensor, chunks, dim=0) 按照某个维度平均分块（最后一个可能小于平均值）
a = torch.Tensor([[1,2,3]])
b = torch.Tensor([[4,5,6],
                  [7,8,9],
                  [10,11,12]])
c = torch.cat((a,b), dim=0) # 合并
print(c)
print()
# 切片
d = torch.chunk(c, 4, dim=0)
print(d)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]), tensor([[7., 8., 9.]]), tensor([[10., 11., 12.]]))


In [33]:
"""
torch.split(tensor, split_size_or_sections, dim=0) : 按照某个维度依照第二个参数给出的list或者int进行分割tensor
"""
# 第二个参数有两种形式。
# 一种是分割份数，这就和torch.chunk（）一样了。
# 第二种这是分割方案，这是一个list，待分割张量将会分割为len（list）份，每一份的大小取决于list中的元素
e = torch.split(c, 2, dim=0)
print(e)

(tensor([[1., 2., 3.],
        [4., 5., 6.]]), tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]]))


In [34]:
f = torch.split(c, [1, 2, 1], dim=0)
print(f)

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.],
        [7., 8., 9.]]), tensor([[10., 11., 12.]]))


In [35]:
# 23. torch.reshape(input, shape)
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.reshape(a, (3, 2))
print(b)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [36]:
# 24. torch.t(input) 只针对2D tensor转置
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.t(a)
print(b)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [37]:
# 25. torch.transpose(input, dim0,dim1): 交换两个维度
a = torch.tensor([[1,2,3],
                  [4,5,6]])

torch.transpose(a, 1, 0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [38]:
# 26. torch.squeeze() 这个函数主要对数据的维度进行压缩，去掉维数为1的的维度
a = torch.tensor([[1],[1]])
torch.squeeze(a)

tensor([1, 1])

In [46]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [39]:
# 27. torch.unsqueeze()这个函数主要是对数据维度进行扩充。给指定位置加上维数为一的维度
a = torch.tensor([1,2,3,4])
torch.unsqueeze(a, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [40]:
# 28. torch.unbind(tensor, dim=0) # 去除某个维度
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(torch.unbind(a, dim=0))

(tensor([1, 2, 3]), tensor([4, 5, 6]))


In [41]:
print(torch.unbind(a, dim=1))

(tensor([1, 4]), tensor([2, 5]), tensor([3, 6]))


In [42]:
# 29. torch.flip(input, dims) : 按照给定维度翻转张量
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

torch.flip(a, [0,1])

tensor([[6, 5, 4],
        [3, 2, 1]])

In [43]:
# 30. torch.rot90(input, k, dims) : 按照指定维度和旋转次数进行张量旋转
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

torch.rot90(a, 1, [0,1])

tensor([[3, 6, 9],
        [2, 5, 8],
        [1, 4, 7]])